import { Activity, ArrowUpRight, Beaker, CheckCircle2, Clock3, Database, FileBarChart, Layers3, ShieldCheck, Sparkles } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { MetricCard, PageHeader, StatusBadge } from '../components/Layout'
import { comparisonData, datasets, experiments, models, trendData } from '../mock/data'

export function DashboardPage() {
  return <>
    <PageHeader eyebrow="研究控制台 · 2026.09" title="实验总览" description="统一管理水印模型、攻击协议与可复现实验结果。" action={<button className="primary-button" onClick={() => window.location.assign('/experiment')}><Beaker size={16} /> 新建实验</button>} />
    <section className="metric-grid"><MetricCard label="已接入模型" value="5" hint="LSB · 频域 · 深度模型" icon={Layers3} accent="blue" /><MetricCard label="数据集" value="4" hint="COCO / DIV2K / DiffusionDB / W-Bench" icon={Database} accent="violet" /><MetricCard label="正式实验记录" value="121,440" hint="formal-v1 · 44 条攻击" icon={FileBarChart} accent="green" /><MetricCard label="最佳完整恢复率" value="96.21%" hint="AM-WAM · +1.60 pp vs WAM" icon={Sparkles} accent="amber" /></section>
    <section className="dashboard-grid"><div className="panel chart-panel"><div className="panel-heading"><div><span className="panel-kicker">趋势</span><h2>模型迭代表现</h2></div><span className="panel-meta">Bit Accuracy / PSNR</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><LineChart data={trendData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" vertical={false} /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis yAxisId="left" domain={[50, 105]} tickLine={false} axisLine={false} tickFormatter={(v) => `${v}%`} /><YAxis yAxisId="right" orientation="right" domain={[35, 55]} tickLine={false} axisLine={false} tickFormatter={(v) => `${v}dB`} /><Tooltip /><Line yAxisId="left" type="monotone" dataKey="accuracy" name="Bit Accuracy" stroke="#2563eb" strokeWidth={3} dot={{ r: 4 }} /><Line yAxisId="right" type="monotone" dataKey="psnr" name="PSNR" stroke="#10b981" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ResponsiveContainer></div></div><div className="panel activity-panel"><div className="panel-heading"><div><span className="panel-kicker">最近活动</span><h2>实验队列</h2></div><Activity size={18} className="muted" /></div><div className="activity-list">{experiments.slice(0, 4).map((item) => <div className="activity-item" key={item.id}><div className="activity-icon">{item.status === '完成' ? <CheckCircle2 size={16} /> : <Clock3 size={16} />}</div><div><strong>{item.model} · {item.attack}</strong><span>{item.dataset} · {item.createdAt}</span></div><StatusBadge tone={item.status === '完成' ? 'green' : 'amber'}>{item.status}</StatusBadge></div>)}</div><button className="text-button" onClick={() => window.location.assign('/results')}>查看全部结果 <ArrowUpRight size={14} /></button></div></section>
    <section className="panel"><div className="panel-heading"><div><span className="panel-kicker">基准对比</span><h2>formal-v1 关键指标</h2></div><StatusBadge tone="blue">690 test · 140 calibration</StatusBadge></div><div className="table-scroll"><table><thead><tr><th>模型</th><th>Bit Accuracy</th><th>完整恢复率</th><th>嵌入 PSNR</th><th>状态</th></tr></thead><tbody>{comparisonData.map((row) => <tr key={row.name}><td><div className="model-cell"><span className="model-dot" style={{ background: models.find((m) => m.name === row.name)?.accent }} />{row.name}</div></td><td><strong>{row.bitAccuracy.toFixed(2)}%</strong></td><td>{row.recovery.toFixed(2)}%</td><td>{row.psnr.toFixed(3)} dB</td><td><StatusBadge>已完成</StatusBadge></td></tr>)}</tbody></table></div></section>
    <section className="dashboard-bottom"><div className="panel mini-panel"><div className="panel-heading"><div><span className="panel-kicker">数据准备</span><h2>数据集状态</h2></div><Database size={18} className="muted" /></div>{datasets.map((dataset) => <div className="progress-row" key={dataset.id}><div><span>{dataset.name}</span><small>{dataset.size}</small></div><div className="progress"><span style={{ width: `${dataset.progress}%` }} /></div><em>{dataset.progress}%</em></div>)}</div><div className="panel mini-panel highlight-panel"><div className="highlight-icon"><ShieldCheck size={22} /></div><div><span className="panel-kicker">实验协议</span><h2>wm-course-v1</h2><p>固定随机种子 42 · 44 类攻击 · 可恢复运行器已启用。</p><button className="text-button" onClick={() => window.location.assign('/attacks')}>查看攻击协议 <ArrowUpRight size={14} /></button></div></div></section>
  </>
}
